settings:
  title: 'ChenYFanの站点监测'
  url: 'https://status.cyfan.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有的系统运行正常'
  notAllmonitorsOperational: '并不是所有的系统运行正常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '非常赞'
  dayInHistogramNotOperational: ' 秒前记录' # xx incident(s) recorded

monitors:
  - id: cyfan-top
    name: ChenYFanの主页
    url: 'https://cyfan.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false


  - id: blog-cyfan-top
    name: ChenYFanの博客
    description: '一个在互联网角落挣扎的小小博客，很小很小' # default=empty
    url: 'https://blog.cyfan.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: tool-cyfan-top
    name: ChenYFanの工具箱
    description: '好康♂的，好玩♀的' # default=empty
    url: 'https://tools.cyfan.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: hexoplusplus-js-org
    name: HPP文档
    description: '不会去看文档' # default=empty
    url: 'https://hexoplusplus.js.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
